### ISSUE TITLE
Use an already exist/Independent  Router impl ?

### ISSUE THREAD

**Issue by krircc** [trek-rs/path-tree#1]
There is [actix_router](https://github.com/actix/actix-net/tree/master/router), but it is Independent，and dont dependent Actix* . It maybe general purpose.
this is one [test](https://github.com/actix/actix-net/blob/master/router/src/router.rs#L146)

**Comment by krircc** [comment]
Oh my bad,  now I find you do [this thing](https://github.com/trek-rs/radix-tree) already,

**Comment by fundon** [comment]
@krircc  This is a basic library. We can use it anywhere.

**Comment by krircc** [comment]
ah, cool, thanks for your explanation.
