### ISSUE TITLE
Matching method requires allocation

### ISSUE THREAD

**Issue by jesskfullwood** [trek-rs/path-tree#4]
Hi, thanks for the library.

It would be good to make it possible to use this library with zero allocations, but it isn't easy to match both the method and path without doing so. Since this is meant for use with HTTP it would be nice if this were possible. 

```rust
let mut router = path_tree::PathTree::new();
router.insert("GET/pet/:petId", 0);
router.insert("POST/pet", 1);
// later
let key = format!("{}{}", req.method(), req.uri().path());  // <-- Allocation, BOO
match router.find(key) {
   // ...
}
```
A better API would be something like:
```rust
let mut router = path_tree::PathTree::new();
router.insert("GET", "/pet/:petId", 0);
router.insert("POST", "/pet", 1);
// later
match router.find(req.method(), req.uri().path()) {  // <- No allocation
   // ...
}
```
Note I am assuming the request object looks something like this: https://docs.rs/http/0.1.17/http/request/struct.Request.html#method.uri

It might be nice to try to avoid allocating for the return type too, for example swapping `Vec` for `SmallVec` (assume that most URIs are only going to have one or two parameters).

**Comment by fundon** [comment]
Currently `path-tree` is very basic library. You can try that https://github.com/trek-rs/router/blob/master/src/lib.rs#L17.

I create other crate https://github.com/trek-rs/router for working with HTTP verbs and path.

**Comment by fundon** [comment]
Maybe I need to change the example.  :)
